### ISSUE TITLE
Bcrypt problems with CircleCi

### ISSUE THREAD

**Issue by andrewMacmurray** [ageuk/companion-app#42]
we've been having problems getting the tests to pass on circle when using bcrypt to verify a password

+ on OSX 10.11 the tests work (my computer)
+ on Ubuntu 15.10 @katbow 's computer the tests were failing when comparing passwords using `bcrypt.compare(password, passwordHash, cb)` (the async version) but passed using the sync version (`bcrypt.compareSync(.....)`)
+ on Circle (on both Ubuntu 12.04 & 14.04 build environments) both methods fail 😭 

Has anyone encountered this problem before?

the problem is here
https://github.com/ageuk/companion-app/blob/hapi-login/lib/login/hapiLoginConfig.js#L13

this is the test that fails
https://github.com/ageuk/companion-app/blob/hapi-login/test/server/login.test.js#L34

it returns `wrong password` instead of `good credentials` on circleCi

Any help would be amazing 😄  👾  ✨

**Comment by nelsonic** [comment]
@andrewMacmurray we've had this before. sample _working_ `circle.yml` file (from OxAbs):
```yml
machine:
  pre:
    - sudo apt-get update; sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 10
  environment:
    DATABASE_URL: postgres://ubuntu:@127.0.0.1:5432/circle_test
  node:
    version: 6.0.0
general:
  artifacts:
    - "coverage"
test:
  post:
    - pip install --user codecov
    - codecov --file coverage/lcov.info --disable search --token=f054ae63-f930-4ad8-ba09-e2b2be42b2d6

dependencies:
  pre:
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
```
